name: ${PROJECT_NAME}

services:
  # MONGO DB
  # -----------------------------------------------------------------
  mongo:
    image: mongo:8
    container_name: "${PROJECT_NAME}-mongo"
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017" 

  # MAILDEV
  # -----------------------------------------------------------------
  maildev:
    image: maildev/maildev
    container_name: ${PROJECT_NAME}-maildev # Nom de l'image
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      - TZ=Europe/France
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025

volumes:
  mongo-data:

networks:
  ${PROJECT_NAME}-network:
