services:
  front:
    container_name: "${PROJECT_NAME}-front"
    image: kevinad/dreamsite-web-front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app/
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - back

  back:
    container_name: "${PROJECT_NAME}-back"
    image: kevinad/dreamsite-cms
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
