name: ${PROJECT_NAME}

services:
  # MONGO DB
  # -----------------------------------------------------------------
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
  
  mongo:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    command: ["--auth", "--storageEngine=wiredTiger"]
    env_file:
      - .env
    networks:
      - project-network

  # MAILDEV
  # -----------------------------------------------------------------
  maildev:
    image: maildev/maildev
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      - TZ=Europe/France
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    networks:
      - project-network

volumes:
  mongo-data:

networks:
  project-network:
    name: ${PROJECT_NAME}-network
