services:
  front:
    image: "kevinad/${PROJECT_NAME}-front:latest"
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env

  back:
    image: "kevinad/${PROJECT_NAME}-back:latest"
    restart: unless-stopped
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - project-network
