name: Image Docker Dev

on:
  push:
    tags:
      - "v*" # Déclenche sur tous les tags commençant par "v"
      - "v*-beta" # Déclenche sur tous les tags contenant "beta"
  workflow_dispatch: # Permet le déclenchement manuel depuis l'interface GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Étape 2 : Configuration de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      # Étape 3 : Construction de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t dreamsite-web-front:${{ github.ref_name }} .

      # Étape 4 : (Optionnel) Push de l'image vers un registre Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag dreamsite-web-front:${{ github.ref_name }} kevinad/dreamsite-web-front:${{ github.ref_name }}
          docker tag dreamsite-web-front:${{ github.ref_name }} kevinad/dreamsite-web-front:latest

          docker push kevinad/dreamsite-web-front:${{ github.ref_name }}
          docker push kevinad/dreamsite-web-front:latest
