name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-back:
    name: Test back (Payload CMS)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    services:
      mongo:
        image: mongo:6
        ports: [27017:27017]
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install back dependencies
        working-directory: back
        run: npm ci

      - name: Build Payload
        working-directory: back
        run: npm run build || echo "No build step needed"

  test-front:
    name: Test front (Next.js)
    runs-on: ubuntu-latest

    needs: test-back

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install front dependencies
        working-directory: front
        run: npm ci

      - name: Build Next.js
        working-directory: front
        run: npm run build
